import re
n=input()
a=input().lower()
a=a.replace('b','1')
a=a.replace('c','1')
a=a.replace('d','2')
a=a.replace('w','2')
a=a.replace('t','3')
a=a.replace('j','3')
a=a.replace('f','4')
a=a.replace('q','4')
a=a.replace('l','5')
a=a.replace('v','5')
a=a.replace('s','6')
a=a.replace('x','6')
a=a.replace('p','7')
a=a.replace('m','7')
a=a.replace('h','8')
a=a.replace('k','8')
a=a.replace('n','9')
a=a.replace('g','9')
a=a.replace('z','0')
a=a.replace('r','0')
a=a.replace(',','')
a=a.replace('.','')
a=re.sub(r"[a-z]", "", a)
a=re.sub(r"[ ]+", " ", a)
a="" if a==" " else a
print(a.strip())