using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Diagnostics;
using System.Collections;

namespace QuestionA
{
    class Program
    {
        static void Main(string[] args)
        {
            string casename = "A-large";//small-attempt0";
            using (StreamReader reader = new StreamReader(casename + ".in"))
            {
                using (StreamWriter writer = new StreamWriter(casename + ".out"))
                {
                    int T = int.Parse(reader.ReadLine());
                    for (int t = 0; t != T; ++t)
                    {
                        // parse test case
                        string[] bases = reader.ReadLine().Split(' ');
                        List<int> b = new List<int>();
                        foreach (string Base in bases)
                        {
                            b.Add(int.Parse(Base));
                        }

                        int index = 0;
                        foreach (int b1 in b)
                        {
                            index |= 1 << (b1 - 2);
                        }

                        int solution = answers[index];

                        Console.WriteLine("Case #{0}: {1}", t + 1, solution);
                        writer.WriteLine("Case #{0}: {1}", t + 1, solution);
                    }
                }
            }
        }

        private static int Solve(List<int> bases)
        {
            for (int n = 2; ; ++n)
            {
                bool yes = true;
                foreach (int b in bases)
                {
                    if (!IsHappyTable(n, b))
                    {
                        yes = false;
                        break;
                    }
                }
                if (yes)
                {
                    return n;
                }
            }
        }

        static bool IsHappyTable(long N, int B)
        {
            while (N > 1000)
            {
                N = SumDigitSquaresInBase(N, B);
            }
            if (N == 1)
            {
                return true;
            }
            return happyTable[(N - 2) * 9 + B - 2];
        }
        static bool IsHappy(long N, int B)
        {
            Dictionary<long, bool> done = new Dictionary<long, bool>();
            while (N != 1)
            {
                N = SumDigitSquaresInBase(N, B);
                if (done.ContainsKey(N))
                {
                    return false;
                }
                done.Add(N, true);
            }
            return true;
        }

        static long SumDigitSquaresInBase(long N, int B)
        {
            long sum = 0;
            while (N != 0)
            {
                int digit = (int)N % B;
                N -= digit;
                N /= B;
                sum += digit * digit;
            }
            return sum;
        }

        // This function generates the answer for every possible subset of bases
        // in 2 ... 10, represented as a binary number.
        static void ComputeAnswers()
        {
            using (StreamWriter writer = new StreamWriter("answer.txt"))
            {
                for (int i = 0; i != 512; ++i)
                {
                    List<int> bases = new List<int>();
                    for (int b = 0; b != 9; ++b)
                    {
                        if ((i & (1 << b)) != 0)
                        {
                            bases.Add(b + 2);
                        }
                    }
                    writer.WriteLine("{0},", Solve(bases));
                    Console.WriteLine(i);
                }
            }
        }

        static int[] answers = new int[512] { 
        2,
2,
3,
3,
2,
2,
3,
3,
5,
5,
23,
23,
5,
5,
23,
23,
6,
6,
79,
79,
6,
6,
79,
79,
49,
49,
79,
79,
49,
49,
79,
79,
7,
7,
143,
143,
7,
7,
143,
143,
7,
7,
143,
143,
7,
7,
143,
143,
49,
49,
2207,
2207,
49,
49,
2207,
2207,
49,
49,
2207,
2207,
49,
49,
2207,
2207,
8,
8,
27,
27,
8,
8,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
216,
216,
3879,
3879,
216,
216,
3879,
3879,
1975,
1975,
3879,
3879,
1975,
1975,
3879,
3879,
1001,
1001,
5719,
5719,
1001,
1001,
5719,
5719,
1001,
1001,
5719,
5719,
1001,
1001,
5719,
5719,
47089,
47089,
47089,
47089,
47089,
47089,
47089,
47089,
48769,
48769,
58775,
58775,
48769,
48769,
58775,
58775,
3,
3,
3,
3,
3,
3,
3,
3,
27,
27,
27,
27,
27,
27,
27,
27,
415,
415,
707,
707,
415,
415,
707,
707,
415,
415,
1695,
1695,
415,
415,
1695,
1695,
125,
125,
143,
143,
125,
125,
143,
143,
125,
125,
143,
143,
125,
125,
143,
143,
2753,
2753,
37131,
37131,
2753,
2753,
37131,
37131,
37131,
37131,
37131,
37131,
37131,
37131,
37131,
37131,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
27,
4977,
4977,
10089,
10089,
4977,
4977,
10089,
10089,
4977,
4977,
23117,
23117,
4977,
4977,
23117,
23117,
6393,
6393,
35785,
35785,
6393,
6393,
35785,
35785,
6393,
6393,
128821,
128821,
6393,
6393,
128821,
128821,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
569669,
7,
7,
13,
13,
7,
7,
13,
13,
7,
7,
23,
23,
7,
7,
23,
23,
44,
44,
79,
79,
44,
44,
79,
79,
49,
49,
79,
79,
49,
49,
79,
79,
7,
7,
167,
167,
7,
7,
167,
167,
7,
7,
7895,
7895,
7,
7,
7895,
7895,
49,
49,
6307,
6307,
49,
49,
6307,
6307,
49,
49,
7895,
7895,
49,
49,
7895,
7895,
97,
97,
219,
219,
97,
97,
219,
219,
219,
219,
219,
219,
219,
219,
219,
219,
608,
608,
3879,
3879,
608,
608,
3879,
3879,
3879,
3879,
3879,
3879,
3879,
3879,
3879,
3879,
34527,
34527,
48041,
48041,
34527,
34527,
48041,
48041,
34527,
34527,
120407,
120407,
34527,
34527,
120407,
120407,
245035,
245035,
697563,
697563,
245035,
245035,
697563,
697563,
245035,
245035,
2688153,
2688153,
245035,
245035,
2688153,
2688153,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
91,
1033,
1033,
6073,
6073,
1033,
1033,
6073,
6073,
4577,
4577,
6073,
6073,
4577,
4577,
6073,
6073,
1337,
1337,
1337,
1337,
1337,
1337,
1337,
1337,
29913,
29913,
120149,
120149,
29913,
29913,
120149,
120149,
71735,
71735,
613479,
613479,
71735,
71735,
613479,
613479,
218301,
218301,
711725,
711725,
218301,
218301,
711725,
711725,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
1177,
9867,
9867,
28099,
28099,
9867,
9867,
28099,
28099,
28099,
28099,
28099,
28099,
28099,
28099,
28099,
28099,
48041,
48041,
48041,
48041,
48041,
48041,
48041,
48041,
246297,
246297,
346719,
346719,
246297,
246297,
346719,
346719,
2662657,
2662657,
4817803,
4817803,
2662657,
2662657,
4817803,
4817803,
11814485,
11814485,
11814485,
11814485,
11814485,
11814485,
11814485,
11814485
        };


        // I ran this function once to generate the table below, and pasted it in
        static void MakeTable()
        {
            using (StreamWriter writer = new StreamWriter("table.txt"))
            {
                for (long n = 2; n <= 1000; n++)
                {
                    for (int B = 2; B <= 10; ++B)
                    {
                        writer.Write("{0}, ", IsHappy(n, B));
                    }
                    writer.WriteLine();
                }
            }
        }

        static bool[] happyTable = new bool[999 * 9] {
            true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, true, false, false, true, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, true, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, true, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, true, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, true, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, true, false, true, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, true, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, true, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, true, false, true, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, true, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, true, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, true, false, true, false, false, 
true, false, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, true, false, true, false, true, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, false, true, false, true, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, true, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, true, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, true, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, true, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, true, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, true, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, true, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, true, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, true, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, true, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, false, true, true, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, true, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, true, false, true, 
true, false, true, false, false, false, false, false, false, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, true, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, true, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, true, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, true, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, false, 
true, false, true, true, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
true, true, true, false, false, false, false, false, false, 
true, false, true, false, false, false, false, false, true, 
        };

    }

    class IOStream
    {
        public IOStream(StreamReader reader)
        {
            this.reader = reader;
        }

        public int ReadInt()
        {
            return int.Parse(ReadString());
        }

        public long ReadLong()
        {
            return long.Parse(ReadString());
        }

        public string ReadString()
        {
            if (parts == null || partNum >= parts.Length)
            {
                ReadMore();
            }
            string rtn = parts[partNum];
            ++partNum;
            return rtn;
        }

        private void ReadMore()
        {
            parts = reader.ReadLine().Split(' ');
            partNum = 0;
        }

        StreamReader reader;
        string[] parts;
        int partNum;
    }
}
