#include<stdio.h>
int main()
{
	freopen("A-large.in","r",stdin);
	freopen("A-large.out","w",stdout);
	int c,o,n,now,i,x_in,y_in,x_ax,y_ax,xx,yy,x[1024],y[1024],m;
	bool b[1024];
	char str[128];
	scanf("%d",&c);
	for(o=1;o<=c;o++)
	{
		scanf("%d",&n);
		now=0;
		for(i=0;i<n;i++)
		{
			scanf("%d%d",x+i,y+i);
			scanf("%s",str);
			if(str[0]=='B')
			{
				b[i]=true;
				now++;
			}
			else
			{
				scanf("%s",str);
				b[i]=false;
			}
		}
		printf("Case #%d:\n",o);
		if(now)
		{
			for(i=0;i<n;i++)
				if(b[i])
					break;
			x_in=x_ax=x[i];
			y_in=y_ax=y[i];
			for(i++;i<n;i++)
				if(b[i])
				{
					if(x[i]>x_ax)
						x_ax=x[i];
					if(x[i]<x_in)
						x_in=x[i];
					if(y[i]>y_ax)
						y_ax=y[i];
					if(y[i]<y_in)
						y_in=y[i];
				}
			scanf("%d",&m);
			while(m--)
			{
				scanf("%d%d",&xx,&yy);
				if(xx>=x_in&&xx<=x_ax&&yy>=y_in&&yy<=y_ax)
					printf("BIRD\n");
				else
				{
					for(i=0;i<n;i++)
						if(!b[i])
						{
							if(x[i]>=x_in&&x[i]<=x_ax)
							{
								if(y[i]>y_ax)
									if(yy>=y[i])
										break;
								if(y[i]<y_in)
									if(yy<=y[i])
										break;
							}
							if(y[i]>=y_in&&y[i]<=y_ax)
							{
								if(x[i]>x_ax)
									if(xx>=x[i])
										break;
								if(x[i]<x_in)
									if(xx<=x[i])
										break;
							}
							if(x[i]<=x_in&&y[i]<=y_in)
							{
								if(xx<=x[i]&&yy<=y[i])
									break;
							}
							if(x[i]>=x_ax&&y[i]<=y_in)
							{
								if(xx>=x[i]&&yy<=y[i])
									break;
							}
							if(x[i]<=x_in&&y[i]>=y_ax)
							{
								if(xx<=x[i]&&yy>=y[i])
									break;
							}
							if(x[i]>=x_ax&&y[i]>=y_ax)
							{
								if(xx>=x[i]&&yy>=y[i])
									break;
							}
						}
					if(i<n)
						printf("NOT BIRD\n");
					else
						printf("UNKNOWN\n");
				}
			}				
		}
		else
		{
			scanf("%d",&m);
			while(m--)
			{
				scanf("%d%d",&xx,&yy);
				for(i=0;i<n;i++)
					if(x[i]==xx&&y[i]==yy)
						break;
				if(i<n)
					printf("NOT BIRD\n");
				else
					printf("UNKNOWN\n");
			}
		}
	}
	return 0;
}
