#!/usr/bin/env python3
import sys


def solve(N: int):
    if N == 0:
        print(0)
        return
    result = ""
    div = 2
    while N != 0:
        divided = N % div
        N -= divided
        if divided != 0:
            result = "1" + result
        else:
            result = "0" + result
        div *= -2
    print(result)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()