#!/usr/bin/env python3
import sys

def countDiv2(n:int):
    sum = 0
    while n % 2 == 0:
        sum += 1
        n //=2
    return sum

def solve(N: int, a: "List[int]"):
    sum = 0
    for ia in a:
        sum += countDiv2(ia)
    print(sum)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [ int(next(tokens)) for _ in range(N) ]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()