a,b,c,d=input().split()
e,f,g,h=input().split()
i,j,k,l=input().split()
m,n,o,p=input().split()
print(p+" "+o+" "+n+" "+m)
print(l+" "+k+" "+j+" "+i)
print(h+" "+g+" "+f+" "+e)
print(d+" "+c+" "+b+" "+a)