s = input()

dic = {
    "WBWBWWBWBWBWWBWBWWBW":"Do",
    "WBWWBWBWBWWBWBWWBWBW":"Re",
    "WWBWBWBWWBWBWWBWBWBW":"Mi",
    "WBWBWBWWBWBWWBWBWBWW":"Fa",
    "WBWBWWBWBWWBWBWBWWBW":"So",
    "WBWWBWBWWBWBWBWWBWBW":"La",
    "WWBWBWWBWBWBWWBWBWWB":"Si"
}

print(dic[s])