#!/usr/bin/env python3
import sys
import math

def solve(n: int):
    ans = n
    for i in range(1, int(math.sqrt(n))+1):
        w = int(n/i)
        ans = min(ans, abs(i-w)+n-(i*w))

    print(ans)

    return


# Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    solve(n)

if __name__ == '__main__':
    main()