#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <ctype.h>

inline static double fsqr(double x) { return x*x; }
inline static int isqr(int x) { return x*x; }
inline static int imin(int x, int y) { return x<y ? x : y; }
inline static int imax(int x, int y) { return x>y ? x : y; }


void do_one_case(int);


int main(int argc, char **argv)
{
  int N, cnum;
  char buf[200];

  fgets(buf, 100, stdin);
  assert(1==sscanf(buf,"%d\n", &N));

  for(cnum=1; cnum<=N; cnum++)
    {
      do_one_case(cnum);
    }

  return 0;
}


void do_one_case(int cnum)
{
  FILE *p, *t, *in;
  int i, n, bit[50], nb;
  char buf[200];
  char b3[3][200];
  char bufx[300];
  char *x;


  t = fopen("temp", "w");

  // input file sqrt5small generated by bc with input:
  //    scale = 100
  //    sqrt(5)
  //    quit
  in = fopen("sqrt5small", "r");

  fprintf(t, "s5 = ");
  while(fgets(buf, 100, in))
    {
      fputs(buf, t);
    }
  fclose(in);

  scanf("%d\n", &n);

  for(nb=0; n; n>>=1)
      bit[nb++] = n&1;

  assert(bit[nb-1]==1);
  assert(nb<40);

  fprintf(t, "a=1\nb=0\n");
  for(i=nb-1; i>=0; i--)
    {
      fprintf(t, "\nc=a*a+5*b*b\nd=2*a*b\na=c\nb=d\n");
      if(bit[i])
          fprintf(t, "c=3*a+5*b\nb=a+3*b\na=c\n");
    }
  fprintf(t, "\na + s5*b\n");
  fclose(t);

  p = popen("bc < temp", "r");
  i = 1;
  strcpy(b3[0],"0000");
  b3[1][0] = b3[2][0] = 0;
  while(fgets(b3[i], 100, p))
    {
      //fprintf(stderr, b3[i]);
      x = strchr(b3[i], '\\');
      if(x) *x=0;
      x = strchr(b3[i], '\n');
      if(x) *x=0;
      if(strchr(b3[i], '.'))
          break;
      i = (i+1)%3;
      b3[i][0] = 0;
    }
  pclose(p);
  strcat(b3[i], ".");

  strcpy(bufx, b3[(i+2)%3]);
  strcat(bufx, b3[i]);
  //fprintf(stderr, "%s\n", bufx);
  x = strchr(bufx, '.');
  assert(x);
  *x = 0;

  printf("Case #%d: %s\n", cnum, x-3);
}
